image: docker:stable
services:
  - docker:dind

stages:
  - test
  - release

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

before_script:
  - echo "$REPO_PASSWORD" | docker login registry.gitlab.com -u "$REPO_USERNAME" --password-stdin
  - docker ps -a
  - docker images -a
  - apk update
  - apk add --no-cache bash

test:
  stage: test
  script:
    - docker build -t $DOCKER_IMAGE .
    - wget -O - https://gitlab.com/rubyonracetracks/docker-debian-buster-common/raw/master/test-image.sh | bash -s $DOCKER_IMAGE
    - wget -O - https://gitlab.com/rubyonracetracks/docker-debian-buster-common/raw/master/push-image.sh | bash -s $DOCKER_IMAGE
