#!/bin/bash
set -e

ABBREV='rvm-rails-adoptatree'

# BEGIN: activate NVM
export NVM_DIR="/home/`whoami`/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
# END: activate NVM

nvm use node # Activate Node

source ~/.rvm/scripts/rvm # Activate RVM

wget -O - https://gitlab.com/rubyonracetracks/docker-debian-buster-rvm-rails-general/raw/master/usr_local_bin/check-rvm-rails-general | bash

echo '###########################'
echo "BEGIN $ABBREV sanity checks"
echo '###########################'

echo '------------'
echo 'phantomjs -v'
phantomjs -v

echo '##############################'
echo "FINISHED $ABBREV sanity checks"
echo '##############################'
