#!/bin/bash
set -e

echo '##############################'
echo 'BEGIN min-stage1 sanity checks'
echo '##############################'

echo '-------------------'
echo 'cat /etc/os-release'
cat /etc/os-release

echo '--------------------------------'
echo 'cat /home/`whoami`/timestamp.txt'
cat /home/`whoami`/timestamp.txt

echo '------'
echo 'whoami'
whoami

echo '-----------'
echo 'sudo whoami'
sudo whoami

echo '--------------'
echo 'sudo --version'
sudo --version

echo '--------------'
echo 'nano --version'
nano --version

echo '#################################'
echo 'FINISHED min-stage1 sanity checks'
echo '#################################'
