#!/bin/bash
set -e

ABBREV='rvm-rails-general'

# BEGIN: activate NVM
export NVM_DIR="/home/`whoami`/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
# END: activate NVM

nvm use node # Activate Node

source ~/.rvm/scripts/rvm # Activate RVM

echo '###########################'
echo "BEGIN $ABBREV sanity checks"
echo '###########################'

echo '--------'
echo 'rvm list'
rvm list

echo '-------'
echo 'ruby -v'
ruby -v

echo '--------'
echo 'rails -v'
rails -v

echo '------------------'
echo 'gem list "^rails$"'
gem list "^rails$"

echo '---------------------'
echo 'gem list "^nokogiri$"'
gem list "^nokogiri$"

echo '---------------'
echo 'gem list "^pg$"'
gem list "^pg$"

echo '----------------'
echo 'gem list "^ffi$"'
gem list "^ffi$"

echo '------------------------'
echo 'gem list "^mailcatcher$"'
gem list "^mailcatcher$"

echo '##############################'
echo "FINISHED $ABBREV sanity checks"
echo '##############################'
