#!/bin/bash
set -e

echo '-------------------'
echo 'BEGIN finalize-user'
echo '-------------------'

DATE=`date +%Y_%m%d_%H%M_%S -u`
echo "Build Date: $DATE" >> /home/`whoami`/timestamp.txt

echo "cat /home/`whoami`/timestamp.txt"
cat /home/`whoami`/timestamp.txt

echo '----------------------'
echo 'FINISHED finalize-user'
echo '----------------------'
