#!/bin/bash
set -e

echo '#############################'
echo 'BEGIN min-stage1-user actions'
echo '#############################'

echo '------------------------------------------------------------------'
echo "Setting /home/`whoami`/.bashrc to automatically record login times"
echo "echo '------------------'" >> /home/`whoami`/.bashrc
echo "echo 'Welcome to Docker!'" >> /home/`whoami`/.bashrc
echo 'DATE=`date +%Y_%m%d_%H%M_%S -u`' >> /home/`whoami`/.bashrc
echo 'echo $DATE >> /home/`whoami`/timestamp.txt' >> /home/`whoami`/.bashrc
echo 'cat /etc/motd' >> /home/`whoami`/.bashrc
echo "echo '------------------------------'" >> /home/`whoami`/.bashrc
echo 'echo "cat /home/`whoami`/timestamp.txt"' >> /home/`whoami`/.bashrc
echo 'cat "/home/`whoami`/timestamp.txt"' >> /home/`whoami`/.bashrc
echo 'cd /home/`whoami`/shared' >> /home/`whoami`/.bashrc

echo '################################'
echo 'FINISHED min-stage1-user actions'
echo '################################'
