#!/bin/bash
set -e

ABBREV='min-stage2'

echo '###########################'
echo "BEGIN $ABBREV-user1 actions"
echo '###########################'

echo '+++++++++++++++++++++'
echo 'BEGIN: installing NVM'
echo '+++++++++++++++++++++'

echo '-------------------------------------------------------------------'
echo "git clone https://github.com/creationix/nvm.git /home/`whoami`/.nvm"
git clone https://github.com/creationix/nvm.git /home/`whoami`/.nvm

echo '---------------------------------------'
echo "cd /home/`whoami`/.nvm && sh install.sh"
cd /home/`whoami`/.nvm && sh install.sh

echo '----'
echo 'wait'
wait

echo '++++++++++++++++++++++++'
echo 'FINISHED: installing NVM'
echo '++++++++++++++++++++++++'

echo '##############################'
echo "FINISHED $ABBREV-user1 actions"
echo '##############################'
