#!/bin/bash
set -e

ABBREV='rvm-rails-sessionizer'

# Set the name of the regular user
REGULAR_USER='vagrant' # To be changed later if necessary

# Execute only in Docker
# Skip in Vagrant
if [ ! -d /home/vagrant ]; then
  REGULAR_USER='winner'
fi

T_BEGIN=$(date +'%s')

echo '--------------------'
echo 'ls -l /usr/local/bin'
ls -l /usr/local/bin

# Prepare apt-get
/usr/local/bin/aptget

# Set environment variables to cut down on annoying warning messages
export DEBIAN_FRONTEND='noninteractive'
export DEBCONF_NOWARNINGS='true'
export HOME=/root
export LC_ALL=C

echo '##########################'
echo "BEGIN $ABBREV-root actions"
echo '##########################'

echo "/usr/local/bin/check-$ABBREV" >> /usr/local/bin/check

echo '++++++++++++++++++++++++++++++++++++++++++++'
echo 'BEGIN installing prerequisites for PhantomJS'
echo '++++++++++++++++++++++++++++++++++++++++++++'

# From https://github.com/OpenTwinCities/adopt-a-tree
# and https://gist.github.com/julionc/7476620

echo '---------------------------------------------------------------------------'
echo 'apt-get install -y libffi-dev build-essential chrpath libssl-dev libxft-dev'
apt-get install -y libffi-dev build-essential chrpath libssl-dev libxft-dev

echo '----------------------------------------------------------------------------------'
echo 'apt-get install -y libfreetype6 libfreetype6-dev libfontconfig1 libfontconfig1-dev'
apt-get install -y libfreetype6 libfreetype6-dev libfontconfig1 libfontconfig1-dev

echo '+++++++++++++++++++++++++++++++++++++++++++++++'
echo 'FINISHED installing prerequisites for PhantomJS'
echo '+++++++++++++++++++++++++++++++++++++++++++++++'

echo '#############################'
echo "FINISHED $ABBREV-root actions"
echo '#############################'

su -c /usr/local/bin/$ABBREV-user $REGULAR_USER
/usr/local/bin/finalize-root
su -c /usr/local/bin/finalize-user $REGULAR_USER
su -c /usr/local/bin/check $REGULAR_USER

T_FINISH=$(date +'%s')
T_ELAPSED=$(($T_FINISH-$T_BEGIN))
echo '--------------------------------'
echo 'Time to modify the Docker image:'
echo "$(($T_ELAPSED / 60)) minutes and $(($T_ELAPSED % 60)) seconds"
