#!/bin/bash
set -e

ABBREV='rvm-rails-adoptatree'
STR_RUBY_VERSIONS="'2.6.3'"
STR_RAILS_VERSIONS="'5.2.3'"
STR_PG_VERSIONS="'1.1.4'"
STR_NOKOGIRI_VERSIONS="'1.10.3'"
STR_FFI_VERSIONS="'1.11.1'"

source ~/.rvm/scripts/rvm # Activate RVM

# BEGIN: activate NVM
export NVM_DIR="/home/`whoami`/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
# END: activate NVM

nvm use node # Activate Node

echo '##########################'
echo "BEGIN $ABBREV-user actions"
echo '##########################'

echo '---------------------------------'
echo 'npm install -g phantomjs-prebuilt'
npm install -g phantomjs-prebuilt

echo '------------'
echo 'phantomjs -v'
phantomjs -v

echo '----------------------------------------------------------------------------------------------'
echo 'wget https://gitlab.com/rubyonracetracks/docker-debian-common/raw/master/rvm-install-rubies.sh'
wget https://gitlab.com/rubyonracetracks/docker-debian-common/raw/master/rvm-install-rubies.sh

echo '------------------------------'
echo 'Updating rvm-install-rubies.sh'
sed -i.bak "s|<STR_RUBY_VERSIONS>|$STR_RUBY_VERSIONS|g" rvm-install-rubies.sh
sed -i.bak "s|<STR_RAILS_VERSIONS>|$STR_RAILS_VERSIONS|g" rvm-install-rubies.sh
sed -i.bak "s|<STR_PG_VERSIONS>|$STR_PG_VERSIONS|g" rvm-install-rubies.sh
sed -i.bak "s|<STR_NOKOGIRI_VERSIONS>|$STR_NOKOGIRI_VERSIONS|g" rvm-install-rubies.sh
sed -i.bak "s|<STR_FFI_VERSIONS>|$STR_FFI_VERSIONS|g" rvm-install-rubies.sh
rm rvm-install-rubies.sh.bak

echo '---------------------------------------------------------------'
echo 'sudo mv rvm-install-rubies.sh /usr/local/bin/rvm-install-rubies'
sudo mv rvm-install-rubies.sh /usr/local/bin/rvm-install-rubies

echo '-----------------------------------------------'
echo 'sudo chmod +x /usr/local/bin/rvm-install-rubies'
sudo chmod +x /usr/local/bin/rvm-install-rubies

/usr/local/bin/rvm-install-rubies


echo '#############################'
echo "FINISHED $ABBREV-user actions"
echo '#############################'
